# Base (Aura default style)
background-color=#282A36
text-color=#F8F8F2
border-color=#BDE0FE

width=420
height=110
padding=10
border-size=1
anchor=top-right
outer-margin=20
default-timeout=5000
max-icon-size=32

# font intentionally unset
# → system default via fontconfig

on-notify=exec paplay /usr/share/sounds/freedesktop/stereo/message.oga

[urgency=low]
default-timeout=3000


[urgency=normal]
default-timeout=5000


[urgency=critical]
background-color=#3B1E2D
border-color=#FF6B6B
text-color=#FFECEC

default-timeout=0


[app-name=Spotify]
invisible=1


[mode=do-not-disturb]
invisible=true
on-notify=none

[mode=do-not-disturb app-name=notify-send]
invisible=false

